### PR TITLE
Some enhancement

### PR DESCRIPTION
**Pull request by rolies106**
I write some simple enhancement : 
- Set default timezone for PHP (it'll throw error on some machine if you leave it unset)
- Add `password` option for redis that need authentication
- Ignore some mac and windows system files

I hope it'll help some one out there :smile:

### CODE REVIEW

**Comment by rolies106** [comment]
Hmm... I run phpunit on `kamisama:master` with same error I think it missing configuration file `src/ResqueBoard/config/Core.php` on `ApiTest.php`

UPDATE :

I tried to include the Core.php but `$_SERVER['SERVER_NAME']` on line 34 thrown an error

**Comment by wa0x6e** [comment]
looks good, I'll take a look into that `date_default_timezone_get()` thing throwing a warning, and it'll be good to merge.

**Comment by wa0x6e** [comment]
In the bootstrap file, maybe changing this line

`date_default_timezone_set(isset($settings['timezone']) ? $settings['timezone'] : date_default_timezone_get());`

to

`date_default_timezone_set(isset($settings['timezone']) ? $settings['timezone'] : 'UTC');` 

will resolve the warning ?

**Comment by rolies106** [comment]
Let me check it first

**Comment by rolies106** [comment]
Ahhhh.... good catch, that solved the issue :smile:

**Comment by wa0x6e** [comment]
After reflection, no, don't do that.

Warning is there because your environment is not properly configured. Just set `date.timezone = 'UTC'` in your php.ini and it'll go away. My patch above will never read the timezone defined in the php.ini.

**Comment by rolies106** [comment]
Hmmm.... I tested it on my staging server and running well (using `date_default_timezone_get()`) so I revert the code

**Pull request merged**
